[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
evm_version = "paris"

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@semaphore-protocol/contracts/=lib/semaphore/packages/contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Test settings
verbosity = 3
fuzz_runs = 256

# Gas reports
gas_reports = ["*"]

[profile.ci]
fuzz_runs = 10000

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
